kind: Rules
metadata:
  namespace: k8s-tutorial
spec:
  - name: "k8s.AddEnvAppLabels"
    description: "Adding environment and application labels using context information from Deploy"
    condition:
      deployedType: k8s.Resources
    processor:
      - type: k8s.MacroFreemarkerAddLabels # example of using 'k8s.MacroFreemarkerAddLabels' macro as a processor
        description: "Using macro and context information for parameters from Deploy"
        parameters:
          application: "#{#ctx.getCurrentDeployedApplication().getName()}" 
          environment: "#{#ctx.getCurrentDeployedApplication().getEnvironment().getName()}"

